### ISSUE TITLE
python version for installation

### ISSUE THREAD

**Issue by javak87** [seisbench/pick-benchmark#1]
Dear developer,
I used python version 3.7 to install this package, but this error pops up:
ERROR: Could not find a version that satisfies the requirement sklearn~=0.24.2 (from versions: 0.0, 0.0.post1)
ERROR: No matching distribution found for sklearn~=0.24.2
I tried to install other python versions, but those versions also have problems with installing seisbench.
could you please tell me which python version is proper for this package?
Best regards,
Javad

**Comment by yetinam** [comment]
Hey @javak87 ,

thanks for making us aware of this issue. Indeed, there was an error in the requirement file. It should be fixed now. Try updating the repository and running the installation skript.
