### ISSUE TITLE
How can I load a model which was saved on GPU on a CPU-only device?

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/pick-benchmark#10]
Hi @yetinam, I've recently trained a model on GPU device using `pytorch-lightning` and I exported the model using a similar way as the `export_model` function in file [export_models.py](https://github.com/seisbench/pick-benchmark/blob/main/benchmark/export_models.py) file.

The exported model works well on the GPU device where it was trained. However, when I copied the model files to a CPU-only device and load the model using `from_pretrained(...)`, the following error occurred:
```bash
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```
However, the built-in models provided in SeisBench can be loaded smoothly, e.g.
```python
model = sbm.EQTransformer.from_pretrained("original")
```
May I ask if you had moved the model weights to cpu using `model.to(torch.device("cpu"))` before you saved the models? I didn't find any code in the file [export_models.py](https://github.com/seisbench/pick-benchmark/blob/main/benchmark/export_models.py) that moves the model to CPU before exporting
https://github.com/seisbench/pick-benchmark/blob/74ba1965b1dd5e770a8358ed83e339a01460e86b/benchmark/export_models.py#L134-L154

I have tried adding `model.model.to(torch.device("cpu"))` before `torch.save(...)`. It works, but I am still not sure whether this would cause any unintended behavior.

The solution provided by the PyTorch document is to set the parameter `map_location=torch.device('cpu')` in `torch.load()`, but there is no way to pass the `map_location` to torch through seisbench (https://github.com/seisbench/seisbench/blob/61ac2df822249fc16b62dfe7da1779ec2e8255bf/seisbench/models/base.py#L515-L543)

Could you give me any advice? Thank you very much!

**Comment by yetinam** [comment]
Hi @zhong-yy,
indeed, there is currently no option to pass the `map_location` to `from_pretrained` or the underlying `SeisBenchModel.load`. Could you maybe write a PR to add this option?
Regarding the option to use `model.model.to(torch.device("cpu"))` before `torch.save()`, that should be absolutely fine and not cause side effects. We didn't need this in `export_models.py`, because we did the actual export on a machine without GPU.

**Comment by zhong-yy** [comment]
Thank you for your quick reply @yetinam .

Yes, I’ll be happy to write a PR to add the map_location option.  Maybe moving the model to cpu (`model.model.to(torch.device("cpu"))` ) before saving the model is a better practice? And the user can choose to move the model to gpu (`model.cuda`) after loading the model if there is a gpu.

**Comment by yetinam** [comment]
You're right, let's not encourage people to save their GPU models. So for now, we do not add the `map_location` parameter. Thanks nonetheless for offering to write the PR.
