### ISSUE TITLE
Training output is inconsistent with the document and the evaluation code

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/pick-benchmark#5]
## Training outputs
I ran a training example with
```bash
python benchmark/train.py --config=configs/stead_phasenet.json
```
and the output in the **weights** folder is
```
weights
└── stead_phasenet
    └── version_0
        ├── checkpoints
        │   └── epoch=99-step=105000.ckpt
        ├── hparams.yaml
        └── metrics.csv
```
There is no **weights/[config]_[config]** folder and **weights/[config]** folder as mentioned in the README document.

## Evaluation
When I tried to do the evaluation using
```bash
python benchmark/eval.py weights/stead_phasenet targets/stead
```
a FileNotFoundError occured:
```
  File "/home/zhongyiyuan/pick-benchmark/benchmark/eval.py", line 210, in <module>
    main(
  File "/home/zhongyiyuan/pick-benchmark/benchmark/eval.py", line 46, in main
    model = load_best_model(model_cls, weights, version.name)
  File "/home/zhongyiyuan/pick-benchmark/benchmark/util.py", line 38, in load_best_model
    return model_cls.load_from_checkpoint(checkpoint_path)
...
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhongyiyuan/pick-benchmark/weights/stead_phasenet_stead_phasenet/0_0/checkpoints/epoch=91-step=96599.ckpt'
```

In addition, the best model seems at the 91th epoth. However, the output in `weights/stead_phasenet/version_0/checkpoints/epoch=99-step=105000.ckpt` seems to be the model at the 99th epoch, which might be the last epoch if indexing starts from 0.

**Comment by zhong-yy** [comment]
The issue of different inconsistent paths is caused by a change in pytorch-lightning https://github.com/Lightning-AI/lightning/pull/12372. Also see https://lightning.ai/forums/t/how-to-get-the-checkpoint-path/327

The issue of saving only the last epoch may be caused by https://github.com/Lightning-AI/lightning/pull/8293. See also https://pytorch-lightning.readthedocs.io/en/stable/generated/CHANGELOG.html#id106.

There is another confusion https://github.com/Lightning-AI/lightning/issues/16636 about the step number, which will also cause the original code to break.

**Comment by yetinam** [comment]
Hi @zhong-yy ,

thanks for reporting this and for digging up the changes in pytorch-lightning causing this. As a workaround, I'd suggest downgrading the pytorch-lightning version to the one indicated in the requirements.txt. This repository is mostly a reference implementation for the benchmark paper, so I do not actively maintain it. If you feel however like updating the code to new versions of pytorch-lightning, I'd be happy to review a PR.

**Comment by zhong-yy** [comment]
Thank you @yetinam 
I previously used the version indicated in the requirements.txt, but encountered an error https://github.com/seisbench/pick-benchmark/issues/3 when training. Then I updated all dependent libraries and it worked. So I prefer to use newer versions
